Fix type annotation for typescript 2.4 (#439)
TypeScript 2.4 has more strict type checking around Promises;
the current code fails with:

.../tf-graph-common/parser.ts(192,3): error TS2322: Type 'Promise<Object>' is not assignable to type 'Promise<NodeDef[]>'.
  Type 'Object' is not assignable to type 'NodeDef[]'.
    The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
      Property 'length' is missing in type 'Object'.

This function is declaring that it returns an arbitrary object, which in TypeScript
is written "any".