plugins: add initializer on base plugin class (#2360)
Summary:
Prior to this change, defining a (possibly dynamically loaded) plugin
without this initializer would yield the rather inscrutable error

```
  File "/VIRTUAL_ENV/tensorboard/plugins/base_plugin.py", line 253, in load
    return self._plugin_class(context)
TypeError: object() takes no parameters
```

whose stack trace does not contain the offending plugin code at all.
(The error is because initializers are effectively inherited in Python.)

Test Plan:
Cherry-pick #2354, delete its example plugin’s `__init__`, and note that
the example still works. (You’ll have to build TensorBoard’s Pip package
and install it into a virtualenv.)

wchargin-branch: plugin-empty-initializer