pip: add `tensorboard.notebook` to Pip package (#1824)
Summary:
Users of the Pip package now have the files necessary to use Jupyter
extensions, by incanting `%load_ext tensorboard.notebook` at the top of
their notebook.

The `notebook` module is also directly exposed on the `tensorboard`
module, so `import tensorboard as tb` followed by `tb.notebook.start`
works (like `program` and `summary`, and unlike `backend` or `plugins`).

Test Plan:
Run `bazel run //tensorboard/pip_package:build_pip_package`, and suppose
that `${WHEEL}` is the path to the emitted Python 3 wheel. Then run

    $ cd "$(mktemp -d)"
    $ virtualenv -q -p python3 ./ve/
    $ . ./ve/bin/activate
    (ve) $ pip install -q tf-nightly-2.0-preview
    (ve) $ pip uninstall -q -y tb-nightly
    (ve) $ pip install -q "${WHEEL}"
    (ve) $ pip install -q jupyter
    (ve) $ jupyter notebook

Then, create a notebook and execute

    %load_ext tensorboard.notebook
    %tensorboard --logdir ~/tensorboard_data/mnist --port 0

to see a new TensorBoard instance.

This process also exercises the smoke test, which passes. Removing the
`def notebook` from `__init__.py` causes that test to fail as expected:

```
Traceback (most recent call last):
  File "<string>", line 6, in <module>
AttributeError: 'module' object has no attribute 'notebook'
```

wchargin-branch: tensorboard-notebook-in-pip