deps: upgrade TensorFlow workspace definition
Summary:
Bazel 0.21.0 includes a breaking change to our transitive dependencies
through TensorFlow. TensorFlow has patched its workspace file
accordingly. This commit upgrades our pinned version of the TensorFlow
workspace to accommodate.

Issue #1710 remains open after this change, because Bazel 0.21.0 has a
further breaking change that causes our tests to fail when run with the
default Bazel flags (see test plan below):
<https://github.com/bazelbuild/bazel/issues/6648>.

Test Plan:
On Bazel 0.21.0, running `bazel query 'deps(//...)'` fails before this
change:

    The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name). You can temporarily allow the old name by using --incompatible_package_name_is_a_function=false
    ERROR: Evaluation of query "deps(//tensorboard)" failed: errors were encountered while computing transitive closure

…but passes after it.

Also, `bazel test --incompatible_strict_action_env=false //...` still
passes on nightly. The new flag is needed due to a breaking change in
Bazel 0.21.0 that this commit does not address.

wchargin-branch: deps-tf-workspace-20181220