Updates references to numpy deprecated type aliases.
Numpy library deprecated some type aliases in version 1.20.0 [1], and
then removed them in version 1.24.0 [2], which was released on Dec 18,
2022.

Without this change, our build would be broken when using numpy version
>= 1.24.0, with error "AttributeError: module 'numpy' has no attribute 'float'".

The fix suggested in release notes from numpy version 1.20.0 is to
replace these types with the equivalent primitive python types. (In this
case, simply `float`.)

[1] numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated
[2] numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations