Fix API demo of debugger V2 (#4843)
`logdir` is no longer a keyword argument for enable_dump_debug_info(). Remove it from the debugger V2 example docs.

Otherwise the caller will get a "TypeError: enable_dump_debug_info() got an unexpected keyword argument 'logdir'" error.