keep using bazel 5 (#6114)
* Motivation for features / changes
Bazel 6.0.0 breaks the current TensorBoard build.

```
$ bazel run tensorboard
ERROR: /usr/local/google/home/bdubois/.cache/bazel/_bazel_bdubois/a027bcadf80e351d5b786d7247b18b84/external/bazel_tools/platforms/BUILD:29:6: in alias rule @bazel_tools//platforms:arm: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /usr/local/google/home/bdubois/.cache/bazel/_bazel_bdubois/a027bcadf80e351d5b786d7247b18b84/external/bazel_tools/platforms/BUILD:29:6: Analysis of target '@bazel_tools//platforms:arm' failed
ERROR: /usr/local/google/home/bdubois/git/tensorboard2/tensorboard/BUILD:20:10: While resolving toolchains for target //tensorboard:tensorboard: invalid registered toolchain '@go_sdk//:go_android_arm': 
ERROR: Analysis of target '//tensorboard:tensorboard' failed; build aborted: 
INFO: Elapsed time: 0.412s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 3 targets conf\
igured)
ERROR: Build failed. Not running target
```

* Technical description of changes
This PR follows the suggestion of this
[comment](https://github.com/bazelbuild/bazel/issues/8622#issuecomment-1358123020)
to keep using Bazel 5 for now.

* Detailed steps to verify changes work correctly (as executed by you)
`bazel run tensorboard` works as before.