manager: improve error messages for exec failures
Summary:
This gives users a more explicit error message for common configuration
errors, like virtualenvs with `--system-site-packages` that mix and
match packages and binaries across environments.

Test Plan:
Automated tests cover changes to `manager.py`. For notebook changes,
build the Pip package, and install it and `IPython` to a new virtualenv.
From an IPython shell, run through all the cases:

```
In [1]: %load_ext tensorboard
In [2]: import os
In [3]: os.environ["PATH"] = ""
In [4]: %tensorboard --logdir logs
Launching TensorBoard...
ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.
In [5]: os.environ["TENSORBOARD_BINARY"] = "/not/likely"
In [6]: %tensorboard --logdir logs
Launching TensorBoard...
ERROR: Could not find '/not/likely' (set by the `TENSORBOARD_BINARY`
environment variable). Please ensure that your PATH contains an
executable `tensorboard` program, or explicitly specify the path to a
TensorBoard binary by setting the `TENSORBOARD_BINARY` environment
variable.
In [7]: os.environ["TENSORBOARD_BINARY"] = "."  # EACCES
In [8]: %tensorboard --logdir logs
Launching TensorBoard...
ERROR: Failed to start '.' (set by the `TENSORBOARD_BINARY`
environment variable): [Errno 13] Permission denied: '.'
```

wchargin-branch: manager-execfailed