application: on plugin load failure, log and continue (#3486)
Summary:
Prior to this change, any exception raised from `loader.load()` would
crash TensorBoard (see, e.g., #3484). As of this patch, we log an error,
drop the plugin, and continue loading.

Test Plan:
Run `bazel run //tensorboard -- --logdir /tmp/logs` in a virtualenv with
`tensorboard-plugin-wit==1.6.0.post3` but *without* the patch in #3485
(i.e., run `git revert e59e9c4f376a`). Note that TensorBoard now prints:

```
E0406 11:00:39.494363 140089282381632 application.py:260] Failed to load plugin WhatIfToolPluginLoader.load; ignoring it.
Traceback (most recent call last):
  File ".../tensorboard/backend/application.py", line 255, in TensorBoardWSGIApp
    plugin = loader.load(context)
  File "/VIRTUAL_ENV/lib/python3.7/site-packages/tensorboard_plugin_wit/wit_plugin_loader.py", line 51, in load
    version = pkg_resources.parse_version(tensorboard.__version__)
AttributeError: module 'tensorboard' has no attribute '__version__'
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.3.0a0 at http://localhost:6006/ (Press CTRL+C to quit)
```

wchargin-branch: application-load-failure-robustness