Ensure flags get initialized
The open source entry-point might not have been invoking tf.app.run() which
a user reports might have caused errors like this to happen:

  absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag
  --debugger_data_server_grpc_port before flags were parsed.

See tensorflow/tensorflow@2652704