build_pip_package: print build log on failure
Summary:
We don’t use `set -x` indiscriminately because build tool output appears
in Bazel logs, and that would be a lot of spam. But we should print
output on failures, to clarify the cause of issues like #2458.

The original version of #2363 had this functionality in the BUILD rule
itself, but @nfelt found that a bit hard to read (fair), so we include
the relevant functionality in `build_pip_package.sh`.

Recommend ignoring whitespace for reading this patch.

Test Plan:
Building `//tensorboard/pip_package` on a machine with no `virtualenv`
binary now prints:

```
ERROR: /home/wchargin/tensorboard/tensorboard/pip_package/BUILD:8:1: Executing genrule //tensorboard/pip_package:pip_package failed (Exit 127) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
+ uname
+ [ Linux = Darwin ]
+ sedi=sed -i
+ command -v virtualenv
Target //tensorboard/pip_package:extract_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
FAILED: Build did NOT complete successfully
```

which is pretty clear that the problem is that `virtualenv` is not
installed. After installing `virtualenv`, the build completes
successfully with no output, as desired.

Running

```
bazel run //tensorboard/pip_package:build_pip_package -- /tmp/nonexistent
```

prints simply

```
fatal: no such output directory: /tmp/nonexistent
```

and exits with `1` rather than printing the whole log.

wchargin-branch: pip-package-error-handling