Fix Bug
Fixed Error:
AttributeError: module 'tensorflow' has no attribute 'io'

since: 
    from tensorboard.compat import tf == tensorflow
    which gives AttributeError: module 'tensorflow' has no attribute 'io'
but we need: 
    from tensorboard.compat import tensorflow_stub as tf

now 'io' can be imported from tensorflow_stub