py3: replace non-`xrange` `six.moves`
Summary:
We use `six.moves` mostly for `xrange`, but also `urllib`, and
occasionally `queue` or `input`. Upgrading `urllib` is context-sensitive
because `six.moves.urllib` always has all submodules, even though
`urllib` may not:

```python
>>> import urllib
>>> urllib.request
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'urllib' has no attribute 'request'
>>> from six.moves import urllib
>>> urllib.request
<module 'six.moves.urllib.request'>
```

We make those moves here, and also clean up the rest of the long tail
such that the remaining moves for `xrange` are all mechanical and can be
fixed in a follow-up commit.

Test Plan:
It suffices that tests pass (but they really have to run; `flake8` does
not suffice here). Remaining:

```
$ git grep -h 'six.*moves' | sort -u
from six.moves import xrange
from six.moves import xrange  # pylint: disable=redefined-builtin
```

wchargin-branch: py3-six-non-xrange-moves