ng: render plugins fetched from backend (#2587)
This change introduces ngrx effects that allows us to interact with the
TensorBoard backend.

This change is not what we ultimately want: it renders all plugins onto
the header instead of showing only active ones.

About testing
This change introduces karma testing instead of the node based testing which admittedly is less than ideal for its speed. It fails with less than ideal error like below.

```
  Message:                               
    TypeError: Cannot read property 'injector' of null
  Stack:                                     
        at <Jasmine>
        at TestBedViewEngine._createCompilerAndModule
...
```

Karma objectively is inferior than running the test in node because
1. source bundling takes time (even if it was simple concat)
2. browser bring-up/tear-down takes time
3. reporting is less than ideal (multi-browser reporter is not well implemented; it probably is configurable though).

If you are type of person who does TDD with ibazel, the difference would be night and day -- node: <1s vs. karma: ~15s.

Although not 100% clear yet, it seems like you can use node test only if the component under test does not leverage any dependency injection (and require the angular JIT/AOT compilation).