server: when no port is specified, try to find one
Summary:
This patch teaches TensorBoard about `--port=default` (which is the new
default value for `--port`). If `--port=default` is specified,
TensorBoard will attempt to bind to port 6006, just as prior to this
patch. If this fails, TensorBoard will try to bind incrementally to
ports 6007, 6008, …, giving up after 10 attempts.

If an explicit port is specified, TensorBoard will not try to search for
other ports; it will fail (as before) if it cannot bind. This is the
only way in which `--port=default` and `--port=6006` differ.

This patch also changes the behavior of one edge case, at least on
Linux. Prior to this patch, explicit port numbers were interpreted
modulo 65536 (TCP ports are u16s), so `--port=71542` and `--port=6006`
had the same behavior. It is now an error on all platforms to specify a
port that does not fit in a u16.

Resolves #1848.

Test Plan:

    $ bazel build //tensorboard

    $ ./bazel-bin/tensorboard/tensorboard --logdir ./logs/ & sleep 2
    [1] 223547
    TensorBoard 1.13.0a0 at http://<hostname>:6006 (Press CTRL+C to quit)

    $ ./bazel-bin/tensorboard/tensorboard --logdir ./logs/ & sleep 2
    [2] 223591
    TensorBoard 1.13.0a0 at http://<hostname>:6007 (Press CTRL+C to quit)

    $ ./bazel-bin/tensorboard/tensorboard --logdir ./logs/ --port default & sleep 2
    [3] 224292
    TensorBoard 1.13.0a0 at http://<hostname>:6008 (Press CTRL+C to quit)

    $ ./bazel-bin/tensorboard/tensorboard --logdir ./logs/ --port 6006 & sleep 2  # should fail
    [4] 225773
    E0214 15:35:08.939894 140033352959744 program.py:232] TensorBoard could not bind to port 6006, it was already in use
    ERROR: TensorBoard could not bind to port 6006, it was already in use
    [4]+  Exit 255                ./bazel-bin/tensorboard/tensorboard --logdir ./logs/ --port 6006

    $ ./bazel-bin/tensorboard/tensorboard --logdir ./logs/ --port 0 & sleep 2
    [4] 226298
    TensorBoard 1.13.0a0 at http://<hostname>:33673 (Press CTRL+C to quit)

    $ for i in {6009..6015}; do ./bazel-bin/tensorboard/tensorboard --logdir ./logs/ --port "$i" & done && sleep 2
    [5] 226638
    [6] 226639
    [7] 226640
    [8] 226641
    [9] 226642
    [10] 226643
    [11] 226644
    TensorBoard 1.13.0a0 at http://<hostname>:6011 (Press CTRL+C to quit)
    TensorBoard 1.13.0a0 at http://<hostname>:6013 (Press CTRL+C to quit)
    TensorBoard 1.13.0a0 at http://<hostname>:6015 (Press CTRL+C to quit)
    TensorBoard 1.13.0a0 at http://<hostname>:6012 (Press CTRL+C to quit)
    TensorBoard 1.13.0a0 at http://<hostname>:6014 (Press CTRL+C to quit)
    TensorBoard 1.13.0a0 at http://<hostname>:6009 (Press CTRL+C to quit)
    TensorBoard 1.13.0a0 at http://<hostname>:6010 (Press CTRL+C to quit)

    $ ./bazel-bin/tensorboard/tensorboard --logdir ./logs/ & sleep 2
    [12] 227173
    E0214 15:35:33.812504 140362460620544 program.py:232] TensorBoard could not bind to any port around 6006 (tried 10 times)
    ERROR: TensorBoard could not bind to any port around 6006 (tried 10 times)

    $ jobs -p | xargs kill

wchargin-branch: port-search