uploader: fix invalid argument error handling (#3325)
Test Plan:
Run `tensorboard dev update-metadata --experiment_id x --name z` (which
raises an `InvalidArgumentError` because `x` is not a valid ID). Before
this patch, this crashes with a stack trace:

```
  File ".../tensorboard/uploader/uploader_main.py", line 478, in execute
    "Server responded: %s" % cm.description()
AttributeError: 'InvalidArgumentError' object has no attribute 'description'
```

Now, it prints a proper error message:

```
Server cannot modify experiment as requested: Invalid experiment ID: 'x'
```

wchargin-branch: uploader-fix-einval