Revert "Add --plugins option to uploader (#3377)"
This reverts commit 343456b5768f290b9d8bc8483fec954c0074f4b7.

Test Plan:
Running `bazel run //tensorboard -- dev list` now works. Previously, it
failed with:

```
  File ".../tensorboard/uploader/uploader_main.py", line 750, in _get_server_info
    server_info = server_info_lib.fetch_server_info(origin, flags.plugins)
AttributeError: 'Namespace' object has no attribute 'plugins'
```

wchargin-branch: revert-uploader-plugins-flag